[include]
paths = ["/etc/ublue-os/topgrade.toml"]

[misc]
no_self_update = true
only = ["distrobox", "brew_cask", "brew_formula", "custom_commands"]
ignore_failures = [
  "distrobox",
  "brew_cask",
  "brew_formula",
  "custom_commands",
]
assume_yes = true
no_retry = false
skip_notify = true

[commands]
"fisher" = "/usr/bin/fish -c 'fisher update'"
"tmux" = "~/.config/tmux/plugins/tpm/bin/update_plugins all"
