[project]
name = "library"
version = "0.1.0"
description = "Python support modules for Ansible"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ansible>=12.2.0",
    "pytest>=9.0.1",
    "pytest-cov>=7.0.0",
    "pytest-mock>=3.15.1",
    "vulture>=2.14",
]

[tool.pytest.ini_options]
addopts = "--cov --cov-report=term"

[tool.coverage.report]
fail_under = 85
show_missing = true
precision = 2
omit = [
  "tests/*",
]
